In [2]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\user\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [6]:
import pandas as pd
import numpy as np
from pathlib import Path
import os

In [10]:
# Get the current working directory (where your notebook is running)
NOTEBOOK_DIR = Path(os.getcwd())

# Navigate to your dataset subfolder
DATA_DIR = NOTEBOOK_DIR.parent /"raw" / "Disease_and_Mobidity_data"

FILE_NAME = "WHO_TOP_CAUSES_OF_DEATH_MALE.csv"
FILE_PATH = DATA_DIR / FILE_NAME

print("Looking for file at:", FILE_PATH)

Looking for file at: C:\Users\USER\Desktop\WORK\RenewedCare\data\raw\Disease_and_Mobidity_data\WHO_TOP_CAUSES_OF_DEATH_MALE.csv

In [11]:
print(DATA_DIR.exists())   # Should be True
print(list(DATA_DIR.glob("*.csv")))  # Should list your CSVs

True
[WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/child_mortality_indicators_nga.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/cholera_adm0_public.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/malaria_indicators_nga.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/maternal_and_reproductive_health_indicators_nga.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/sexually_transmitted_infections_indicators_nga.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/tuberculosis_indicators_nga.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/WHO_TOP_CAUSES_OF_DEATH_BOTH_GENDERS.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/WHO_TOP_CAUSES_OF_DEATH_FEMALE.csv'), WindowsPath('C:/Users/USER/Desktop/WORK/RenewedCare/data/raw/Disease_and_Mobidity_data/WHO_TOP_CAUSES_OF_DEATH_MALE.csv')]

In [9]:
print(os.getcwd())

C:\Users\USER\Desktop\WORK\RenewedCare\data\scripts

In [12]:
# Load dataset
df = pd.read_csv(FILE_PATH)

# === 1. Check basic info ===
print("‚úÖ Dataset loaded successfully!")
print(f"Number of rows: {df.shape[0]}")
print(f"Number of columns: {df.shape[1]}")
print("\nüìã Column names:")
print(df.columns.tolist())

‚úÖ Dataset loaded successfully!
Number of rows: 24522
Number of columns: 5

üìã Column names:
['DIM_COUNTRY_CODE', 'DIM_YEAR_CODE', 'DIM_GHECAUSE_TITLE', 'DIM_SEX_CODE', 'VAL_DTHS_RATE100K_NUMERIC']

In [13]:
# === 2. Check for missing values ===
print("\nüîç Missing values summary:")
missing_summary = df.isnull().sum().sort_values(ascending=False)
missing_percent = (df.isnull().mean() * 100).sort_values(ascending=False)

# Combine both into a single DataFrame for clarity
missing_report = pd.DataFrame({
    'Missing Values': missing_summary,
    'Percentage (%)': missing_percent.round(2)
})

# Show only columns with missing values
print(missing_report[missing_report['Missing Values'] > 0])

# === 3. (Optional) Show quick stats for numeric columns ===
print("\nüìä Quick numeric summary:")
display(df.describe())

üîç Missing values summary:
Empty DataFrame
Columns: [Missing Values, Percentage (%)]
Index: []

üìä Quick numeric summary:

       DIM_YEAR_CODE  VAL_DTHS_RATE100K_NUMERIC
count        24522.0               24522.000000
mean          2021.0                   6.173073
std              0.0                  24.064276
min           2021.0                   0.000000
25%           2021.0                   0.000000
50%           2021.0                   0.160000
75%           2021.0                   2.730000
max           2021.0                 615.610000

In [14]:
# Columns of interest
cols_of_interest = ['DIM_COUNTRY_CODE', 'DIM_GHECAUSE_TITLE', 'DIM_SEX_CODE']

# Check they exist (helps prevent typos or missing columns)
for col in cols_of_interest:
    if col not in df.columns:
        print(f"‚ö†Ô∏è Column not found: {col}")
    else:
        distinct_values = df[col].dropna().unique()
        print(f"\nüîπ Distinct values in {col} ({len(distinct_values)} unique):")
        print(distinct_values)

üîπ Distinct values in DIM_COUNTRY_CODE (183 unique):
['AFG' 'AGO' 'ALB' 'ARE' 'ARG' 'ARM' 'ATG' 'AUS' 'AUT' 'AZE' 'BDI' 'BEL'
 'BEN' 'BFA' 'BGD' 'BGR' 'BHR' 'BHS' 'BIH' 'BLR' 'BLZ' 'BOL' 'BRA' 'BRB'
 'BRN' 'BTN' 'BWA' 'CAF' 'CAN' 'CHE' 'CHL' 'CHN' 'CIV' 'CMR' 'COD' 'COG'
 'COL' 'COM' 'CPV' 'CRI' 'CUB' 'CYP' 'CZE' 'DEU' 'DJI' 'DNK' 'DOM' 'DZA'
 'ECU' 'EGY' 'ERI' 'ESP' 'EST' 'ETH' 'FIN' 'FJI' 'FRA' 'FSM' 'GAB' 'GBR'
 'GEO' 'GHA' 'GIN' 'GMB' 'GNB' 'GNQ' 'GRC' 'GRD' 'GTM' 'GUY' 'HND' 'HRV'
 'HTI' 'HUN' 'IDN' 'IND' 'IRL' 'IRN' 'IRQ' 'ISL' 'ISR' 'ITA' 'JAM' 'JOR'
 'JPN' 'KAZ' 'KEN' 'KGZ' 'KHM' 'KIR' 'KOR' 'KWT' 'LAO' 'LBN' 'LBR' 'LBY'
 'LCA' 'LKA' 'LSO' 'LTU' 'LUX' 'LVA' 'MAR' 'MDA' 'MDG' 'MDV' 'MEX' 'MKD'
 'MLI' 'MLT' 'MMR' 'MNE' 'MNG' 'MOZ' 'MRT' 'MUS' 'MWI' 'MYS' 'NAM' 'NER'
 'NGA' 'NIC' 'NLD' 'NOR' 'NPL' 'NZL' 'OMN' 'PAK' 'PAN' 'PER' 'PHL' 'PNG'
 'POL' 'PRK' 'PRT' 'PRY' 'QAT' 'ROU' 'RUS' 'RWA' 'SAU' 'SDN' 'SEN' 'SGP'
 'SLB' 'SLE' 'SLV' 'SOM' 'SRB' 'SSD' 'STP' 'SUR' 'SVK' 'SVN' 'SWE' 'SWZ'
 'SYC' 'SYR' 'TCD' 'TGO' 'THA' 'TJK' 'TKM' 'TLS' 'TON' 'TTO' 'TUN' 'TUR'
 'TZA' 'UGA' 'UKR' 'URY' 'USA' 'UZB' 'VCT' 'VEN' 'VNM' 'VUT' 'WSM' 'YEM'
 'ZAF' 'ZMB' 'ZWE']

üîπ Distinct values in DIM_GHECAUSE_TITLE (134 unique):
['Syphilis' 'Genital herpes' 'Diphtheria' 'African trypanosomiasis'
 'Dengue' 'Rabies' 'Lower respiratory infections' 'Vitamin A deficiency'
 'Liver cancer' 'Bladder cancer' 'Larynx cancer' 'Thalassaemias'
 'Bipolar disorder' 'Rheumatic heart disease' 'Urolithiasis'
 'Back and neck pain' 'Oral conditions' 'Sudden infant death syndrome'
 'Fire, heat and hot substances' 'Tuberculosis' 'HIV/AIDS'
 'Acute hepatitis B' 'Onchocerciasis' 'Protein-energy malnutrition'
 'Stomach cancer' 'Ovary cancer' 'Childhood behavioural disorders'
 'Non-migraine headache' 'Chronic obstructive pulmonary disease'
 'Gastritis and duodenitis' 'Inflammatory bowel disease' 'Kidney diseases'
 'Osteoarthritis' 'Poisonings' 'Exposure to mechanical forces'
 'Collective violence and legal intervention' 'Trichomoniasis'
 'Meningitis' 'Leishmaniasis' 'Yellow fever' 'Trichuriasis'
 'Mouth and oropharynx cancers' 'Cervix uteri cancer' 'Testicular cancer'
 'Kidney cancer' 'Diabetes mellitus' 'Eating disorders'
 'Multiple sclerosis' 'Other vision loss' 'Self-harm' 'Chlamydia'
 'Measles' 'Acute hepatitis E' 'Chagas disease' 'Echinococcosis'
 'Food-bourne trematodes' 'Leprosy' 'Maternal conditions'
 'Birth asphyxia and birth trauma' 'Melanoma and other skin cancers'
 'Brain and nervous system cancers' 'Thyroid cancer'
 'Sickle cell disorders and trait' 'Drug use disorders'
 'Parkinson disease' 'Uncorrected refractive errors' 'Stroke'
 'Cirrhosis of the liver' 'Gynecological diseases' 'Drowning'
 'Whooping cough' 'Malaria' 'Trachoma' 'Upper respiratory infections'
 'Iron-deficiency anaemia' 'Pancreas cancer' 'Lymphomas, multiple myeloma'
 'Schizophrenia' 'Glaucoma' 'Hypertensive heart disease' 'Asthma'
 'Paralytic ileus and intestinal obstruction' 'Pancreatitis'
 'Benign prostatic hyperplasia' 'Gout' 'Falls' 'Diarrhoeal diseases'
 'Acute hepatitis C' 'Iodine deficiency' 'Colon and rectum cancers'
 'Prostate cancer' 'Depressive disorders' 'Autism and Asperger syndrome'
 'Idiopathic intellectual disability' 'Migraine' 'Other hearing loss'
 'Rheumatoid arthritis' 'Road injury' 'Interpersonal violence'
 'Encephalitis' 'Acute hepatitis A' 'Lymphatic filariasis'
 'Hookworm disease' 'COVID-19' 'Oesophagus cancer' 'Breast cancer'
 'Corpus uteri cancer' 'Gallbladder and biliary tract cancer'
 'Mesothelioma' 'Anxiety disorders' 'Epilepsy' 'Macular degeneration'
 'Cardiomyopathy, myocarditis, endocarditis' 'Appendicitis'
 'Skin diseases' 'Gonorrhoea' 'Tetanus' 'Schistosomiasis' 'Cysticercosis'
 'Ascariasis' 'Otitis media' 'Preterm birth complications'
 'Neonatal sepsis and infections' 'Trachea, bronchus, lung cancers'
 'Leukaemia' 'Alcohol use disorders'
 'Alzheimer disease and other dementias' 'Cataracts'
 'Ischaemic heart disease' 'Peptic ulcer disease'
 'Gallbladder and biliary diseases' 'Infertility' 'Congenital anomalies'
 'Natural disasters']

üîπ Distinct values in DIM_SEX_CODE (1 unique):
['MLE']

In [15]:
# Normalize text (lowercase) to avoid capitalization mismatches
df['DIM_GHECAUSE_TITLE'] = df['DIM_GHECAUSE_TITLE'].astype(str).str.lower()
df['DIM_COUNTRY_CODE'] = df['DIM_COUNTRY_CODE'].astype(str).str.upper()

# List of diseases to look for
target_diseases = [
    "malaria", "tuberculosis", "cholera", "chlamydia", "gonorrhea",
    "syphilis", "trichomoniasis", "public lice", "crabs", "scabies",
    "mycoplasma genitalium", "hiv", "herpes", "human papillomavirus",
    "hpv", "hepatitis", "mpox"
]

# Create a mask to check if any disease name appears in the GHECAUSE title
mask = df['DIM_GHECAUSE_TITLE'].apply(
    lambda x: any(disease in x for disease in target_diseases)
)

# Filter the dataset
disease_df = df[mask].copy()

# Group by disease and country
result = (
    disease_df.groupby(['DIM_GHECAUSE_TITLE', 'DIM_COUNTRY_CODE'])
    .size()
    .reset_index(name='Count')
    .sort_values(by=['DIM_GHECAUSE_TITLE', 'Count'], ascending=[True, False])
)

# Show result
print("Diseases and countries they appear in:")
display(result)

Diseases and countries they appear in:

     DIM_GHECAUSE_TITLE DIM_COUNTRY_CODE  Count
0     acute hepatitis a              AFG      1
1     acute hepatitis a              AGO      1
2     acute hepatitis a              ALB      1
3     acute hepatitis a              ARE      1
4     acute hepatitis a              ARG      1
...                 ...              ...    ...
2008       tuberculosis              WSM      1
2009       tuberculosis              YEM      1
2010       tuberculosis              ZAF      1
2011       tuberculosis              ZMB      1
2012       tuberculosis              ZWE      1

[2013 rows x 3 columns]

In [17]:
# Function to count distinct countries for each disease
def count_countries_per_disease(df, diseases):
    counts = []
    for disease in diseases:
        mask = df['DIM_GHECAUSE_TITLE'].str.contains(disease, case=False, na=False)
        countries = df.loc[mask, 'DIM_COUNTRY_CODE'].unique()
        counts.append({
            'Disease': disease,
            'Distinct Countries': len(countries),
            'Country List': list(countries)
        })
    return pd.DataFrame(counts).sort_values(by='Distinct Countries', ascending=False)

# Apply function
country_counts = count_countries_per_disease(df, target_diseases)

# Display results
print("‚úÖ Distinct country counts per disease:")
display(country_counts)

‚úÖ Distinct country counts per disease:

,Disease,Distinct Countries,Country List
0,malaria,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
11,hiv,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
15,hepatitis,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
3,chlamydia,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
5,syphilis,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
6,trichomoniasis,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
1,tuberculosis,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
12,herpes,183,"[AFG, AGO, ALB, ARE, ARG, ARM, ATG, AUS, AUT, ..."
14,hpv,0,[]
13,human papillomavirus,0,[]
8,crabs,0,[]
10,mycoplasma genitalium,0,[]
9,scabies,0,[]
7,public lice,0,[]
4,gonorrhea,0,[]
2,cholera,0,[]
16,mpox,0,[]

In [31]:
# Filter to only rows that contain one of the target diseases
mask = df['diseases'].apply(
    lambda x: any(disease in x for disease in target_diseases)
)

# Keep only matching rows (drop all others)
filtered_df = df[mask].copy()

print(f"‚úÖ Filtered dataset now contains {len(filtered_df)} rows (from {len(df)} originally).")
print(f"‚úÖ Diseases included: {filtered_df['diseases'].nunique()} unique causes.")

# Optional: inspect what remains
display(filtered_df.head())

‚úÖ Filtered dataset now contains 2013 rows (from 24522 originally).
‚úÖ Diseases included: 11 unique causes.

   country_code  year           diseases  sex  death_rate
0           AFG  2021           syphilis  MLE        1.53
1           AFG  2021     genital herpes  MLE        0.00
19          AFG  2021       tuberculosis  MLE       17.29
20          AFG  2021           hiv/aids  MLE        2.58
21          AFG  2021  acute hepatitis b  MLE        2.38

In [32]:
print("Number of rows left:", len(filtered_df))

Number of rows left: 2013

In [27]:
# Rename columns (matching lowercase names)
df = df.rename(columns={
    "dim_ghecause_title": "diseases",
    "dim_country_code": "country_code",
    "dim_year_code": "year",
    "dim_sex_code": "sex",
    "val_dths_rate100k_numeric": "death_rate"
})

# Verify the rename
print(df.columns.tolist())

['country_code', 'year', 'diseases', 'sex', 'death_rate']

In [34]:
# Case-insensitive filtering for partial matches
mask = df["diseases"].str.lower().apply(
    lambda x: any(disease in x for disease in target_diseases)
)

filtered_df = df[mask].copy()

print(f"‚úÖ Filtered dataset now contains {len(filtered_df)} rows (from {len(df)} originally).")
print(f"‚úÖ Diseases included: {filtered_df['diseases'].nunique()} unique causes.")

# Define output file path
output_path = NOTEBOOK_DIR.parent / "processed" / "WHO_TOP_CAUSES_OF_DEATH_BOTH_GENDERS.csv"

# Save to CSV
filtered_df.to_csv(output_path, index=False)

print(f"Filtered data saved to: {output_path}")
print(f"Number of rows left: {len(filtered_df)}")

‚úÖ Filtered dataset now contains 2013 rows (from 24522 originally).
‚úÖ Diseases included: 11 unique causes.
Filtered data saved to: C:\Users\USER\Desktop\WORK\RenewedCare\data\processed\WHO_TOP_CAUSES_OF_DEATH_BOTH_GENDERS.csv
Number of rows left: 2013